version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: install lint tool
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
      - run:
          name: golangci-lint
          command: make lint
      - run:
          name: install node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: install serverless
          command: 'sudo npm install -g serverless'
      - deploy:
          name: deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                make deployprod
              else
                make deploy
              fi

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context: aws-serverless
