version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18

jobs:
  deploy:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: install node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: install serverless
          command: 'sudo npm install -g serverless'
      - deploy:
          name: deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                make deployprod
              else
                make deploy
              fi

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context: aws-serverless
